import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const webDirectory = dirname(dirname(fileURLToPath(import.meta.url)));
const productionDirectory = join(webDirectory, "..", "public-repo", "herald", "harvester", "production");
const generatedFile = join(webDirectory, "src", "generated", "heralds.ts");
const filenamePattern = /^(?<domain>.+)-(?<number>[1-9]\d*)\.json$/;

async function readHeralds(kind) {
  const directory = join(productionDirectory, kind);
  const files = await readdir(directory);
  const heralds = await Promise.all(
    files
      .sort((left, right) => left.localeCompare(right))
      .filter((file) => filenamePattern.test(file))
      .map(async (file) => {
        const match = filenamePattern.exec(file);
        const config = JSON.parse(await readFile(join(directory, file), "utf8"));

        if (typeof config.name !== "string" || typeof config.version !== "string") {
          throw new Error(`${kind}/${file} must contain string name and version fields.`);
        }

        return {
          domain: match.groups.domain,
          file,
          name: config.name,
          version: config.version,
        };
      }),
  );

  return heralds;
}

const [nameHeralds, threadHeralds] = await Promise.all([readHeralds("name"), readHeralds("thread")]);
const threadDomains = new Set(threadHeralds.map((herald) => herald.domain));
const nameDomains = new Set(nameHeralds.map((herald) => herald.domain));
const supportedDomains = [...new Set([...threadDomains].filter((domain) => nameDomains.has(domain)))].sort();

const sites = supportedDomains.map((domain) => ({
  domain,
  names: nameHeralds.filter((herald) => herald.domain === domain).map(({ domain: _domain, ...herald }) => herald),
  threads: threadHeralds.filter((herald) => herald.domain === domain).map(({ domain: _domain, ...herald }) => herald),
}));

const source = `// Generated by scripts/generate-heralds.mjs. Do not edit manually.\n\nexport type Herald = {\n  file: string;\n  name: string;\n  version: string;\n};\n\nexport type HeraldSite = {\n  domain: string;\n  names: Herald[];\n  threads: Herald[];\n};\n\nexport const heraldSites: HeraldSite[] = ${JSON.stringify(sites, null, 2)};\n`;

await writeFile(generatedFile, source);
